### ISSUE TITLE
0pdd didn't raise the issues for the puzzlers which exists in "snapshot" xml

### ISSUE THREAD

**Issue by dgroup** [yegor256/0pdd#241] opened 2018-09-22 10:01 UTC
Hi @yegor256 ,

The project was linked with 0pdd
1. `.0pdd` content
    ```bash
      --source=.
      --verbose
      --exclude target/**/*
      --exclude docs
      --rule min-estimate:30
      --rule max-estimate:90
   ```
2. `.0pdd.yml` content
    ```yml
     errors:
        - yurii.dubinka@gmail.com
     # alerts:
        #  suppress:
        #    - on-found-puzzle
        #    - on-lost-puzzle
        #    - on-scope
        #  github:
        #    - dgroup
        #format:
        #  - short-title
        #  - title-length=100
    
     tags:
       - pdd
       - bug
    ```
3. @0pdd addes as contributor
4. The integration hook also configured
<img width="764" alt="screen shot 2018-09-22 at 3 14 18 pm" src="https://user-images.githubusercontent.com/1651114/45915869-608de680-be7a-11e8-87e7-85a8f349cdf3.png">

According to http://www.0pdd.com/p?name=dgroup/ka25 
there are 2 active issues from `todo.md` file, but it was removed as not required long time ago.

According to http://www.0pdd.com/snapshot?name=dgroup/ka25
there are 2 pendind puzzlers which should be created.

I've pushed several commits, but there is no action from @0pdd side.
Expected result:
1. The following puzzlers are removed
    http://www.0pdd.com/p?name=dgroup/ka25
    ```
     7-18f0c0e2 todo.md:2-2 30min
     8-f87da0bd todo.md:3-3 30min
   ```
2. The 2 issues are raised for the `14-9ca373f0` and `13-23e31113` accordinly.

**Comment by 0crat** [comment] 2018-09-22 10:01
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-09-22 10:01
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment] 2018-10-15 06:48
@dgroup this seems to be the issue:

```
Octokit::NotFound: PATCH https://api.github.com/user/memberships/orgs/fidals: 404 - Not Found // See: https://developer.github.com/v3/orgs/members/#edit-your-organization-membership
  from octokit/response/raise_error.rb:16:in `on_complete'
  from faraday/response.rb:9:in `block in call'
  from faraday/response.rb:61:in `on_complete'
  from faraday/response.rb:8:in `call'
  from octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  from octokit/middleware/follow_redirects.rb:61:in `call'
  from faraday/request/retry.rb:128:in `call'
  from faraday/rack_builder.rb:143:in `build_response'
  from faraday/connection.rb:387:in `run_request'
  from faraday/connection.rb:175:in `patch'
  from sawyer/agent.rb:94:in `call'
  from octokit/connection.rb:156:in `request'
  from octokit/connection.rb:46:in `patch'
  from octokit/client/organizations.rb:693:in `update_organization_membership'
  from objects/github_invitations.rb:37:in `block in accept_orgs'
  from objects/github_invitations.rb:36:in `each'
  from objects/github_invitations.rb:36:in `accept_orgs'
  from 0pdd.rb:246:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1097:in `block in dispatch!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:1094:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1502:in `block in call'
  from sinatra/base.rb:1729:in `synchronize'
  from sinatra/base.rb:1502:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

**Comment by 0crat** [comment] 2018-10-15 06:57
Thanks for your contribution, @dgroup[/z](https://www.0crat.com/u/dgroup)! If you would be a member of [the project](https://www.0crat.com/p/C3T46CUJJ), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment] 2018-10-15 06:57
The job [#241](https://github.com/yegor256/0pdd/issues/241) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/2880660116); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2018-10-15 06:58
Job `gh:yegor256/0pdd#241` already assigned to @yegor256, can't assign to @yegor256

**Comment by yegor256** [comment] 2018-10-15 07:01
@rultor release, tag is `0.30.6`

**Comment by 0crat** [comment] 2018-10-15 07:04
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment] 2018-10-15 11:55
@dgroup I believe the problem is gone. Can you please re-test and confirm?

**Comment by dgroup** [comment] 2018-11-18 18:14
Hi @yegor256,
Looks like i've understood the root cause of this problem.
0pdd doesn't work with `non-master` default branches. 

The tickets were raised once i've changed the default branch from `dev` to `master`.
Please add this information to the docs.
Stacktrace which allows me to understand it, just for the history
```java
set -x && set -e && set -o pipefail && cd /tmp/0pdd20181118-4-nlbaf3/dgroup/vcs && git config --local core.autocrlf false && git reset origin/dev --hard --quiet && git clean --force -d && git fetch --quiet && git checkout dev && git rebase --abort || true && git rebase --autostash --strategy-option=theirs origin/dev [1]:
bash: warning: setlocale: LC_ALL: cannot change locale (UTF-8)
+ set -e
+ set -o pipefail
+ cd /tmp/0pdd20181118-4-nlbaf3/dgroup/vcs
+ git config --local core.autocrlf false
+ git reset origin/dev --hard --quiet
fatal: ambiguous argument 'origin/dev': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git  [...] -- [...]'
+ true
+ git rebase --autostash --strategy-option=theirs origin/dev
fatal: Needed a single revision
invalid upstream origin/dev



/app/objects/exec.rb:60:in `block (2 levels) in run'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/open3.rb:205:in `popen_run'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/open3.rb:95:in `popen3'
/app/objects/exec.rb:54:in `block in run'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/app/objects/exec.rb:53:in `run'
/app/objects/git_repo.rb:110:in `pull'
/app/objects/git_repo.rb:75:in `push'
/app/objects/job.rb:36:in `proceed'
/app/objects/job_starred.rb:33:in `proceed'
/app/objects/job_recorded.rb:32:in `proceed'
/app/objects/job_emailed.rb:35:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:48:in `exclusive'
/app/objects/job_detached.rb:36:in `block in proceed'
/app/objects/job_detached.rb:36:in `fork'
/app/objects/job_detached.rb:36:in `proceed'
/app/0pdd.rb:350:in `block in '
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/handler/webrick.rb:86:in `service'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
```

**Closed** 2018-12-26 14:19 UTC
Labels: scope

**Comment by 0crat** [comment] 2018-12-26 14:39
The job [#241](https://github.com/yegor256/0pdd/issues/241) is now out of scope

**Comment by 0crat** [comment] 2018-12-26 14:39
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
