### ISSUE TITLE
Duplicate Tickets - Round 2

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/0pdd#75] opened 2017-04-16 18:51 UTC
This may or may not be the same underlying issue as #40 .

If it is, then #40 isn't fixed yet. It could be something else also.

However, we were seeing duplicate tickets getting created in our repository yesterday:
https://github.com/EnigmaDragons/MegaBuy/issues/106
https://github.com/EnigmaDragons/MegaBuy/issues/107
https://github.com/EnigmaDragons/MegaBuy/issues/108
https://github.com/EnigmaDragons/MegaBuy/issues/109
https://github.com/EnigmaDragons/MegaBuy/issues/110
https://github.com/EnigmaDragons/MegaBuy/issues/111
https://github.com/EnigmaDragons/MegaBuy/issues/112
https://github.com/EnigmaDragons/MegaBuy/issues/113

I first noticed a duplicate ticket created with a merge commit, when GitHub seemed to think that merged code was "new". That might be something to investigate.

**Comment by 0crat** [comment] 2017-04-16 18:51
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment] 2017-04-16 18:53
@SilasReinagel thanks! Will investigate and fix soon.

**Comment by yegor256** [comment] 2017-04-25 11:51
@SilasReinagel I think the problem is fixed in #80 This won't happen again.

**Comment by 0crat** [comment] 2017-05-31 07:44
Oops! Job `gh:yegor256/0pdd#75` was not in scope

**Closed** 2017-05-31 07:44 UTC
