### ISSUE TITLE
content-type mistake for error pages

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#135] opened 2017-10-16 07:38 UTC
Looks like we're setting incorrect content-type for error pages (404 and 400). That's why this is what I'm getting for http://www.0pdd.com/snapshot?name=0/_qsdssd
![screen shot 2017-10-16 at 10 37 25 am](https://user-images.githubusercontent.com/526301/31600171-1925f798-b25e-11e7-967b-d3e1c5d2fcde.png)

**Comment by yegor256** [comment] 2017-10-16 07:38
@0crat assign @tedtoer

**Comment by 0crat** [comment] 2017-10-16 07:39
> @0crat assign @tedtoer  ([here](https://github.com/yegor256/0pdd/issues/135#issuecomment-336804830))

@yegor256 Job `gh:yegor256/0pdd#135` assigned to @tedtoer, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment] 2017-10-16 07:40
Bug was reported: +15 points just awarded to @yegor256, total is [+4055](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment] 2017-11-14 14:56
@tedtoer this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment] 2017-11-14 15:14
@tedtoer resigned from `gh:yegor256/0pdd#135`, please stop working.

**Comment by 0crat** [comment] 2017-11-14 15:14
Oops! Job `gh:yegor256/0pdd#135` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-11-14 15:15
Oops! Job `gh:yegor256/0pdd#135` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-11-14 15:16
Oops! Job `gh:yegor256/0pdd#135` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-11-14 15:17
Oops! Job `gh:yegor256/0pdd#135` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-12-17 10:28
@tedtoer resigned from `gh:yegor256/0pdd#135`, please stop working.

**Comment by 0crat** [comment] 2017-12-17 23:58
Job `gh:yegor256/0pdd#135` assigned to @tedtoer. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment] 2017-12-27 19:20
@tedtoer resigned from `gh:yegor256/0pdd#135`, please stop working.

**Comment by SilasReinagel** [comment] 2018-04-11 03:13
@yegor256 Rultor closed this without checking that the issue was fixed. Also, the fix attempt didn't work. I have a new PR.

**Comment by 0crat** [comment] 2018-04-11 17:57
> @0crat status ([here](https://github.com/yegor256/0pdd/issues/135#issuecomment-380541352))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#135](https://github.com/yegor256/0pdd/issues/135) is [in scope](http://www.zerocracy.com/policy.html#14) for 6mon
  * The role is `DEV`
  * The job is assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel) for [9days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @tedtoer[/z](https://www.0crat.com/u/tedtoer): User was resigned from the ticket
    * @valentjedi[/z](https://www.0crat.com/u/valentjedi): User was resigned from the ticket
    * @prondzyn[/z](https://www.0crat.com/u/prondzyn): User was resigned from the ticket
    * @vl3[/z](https://www.0crat.com/u/vl3): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3T46CUJJ?q=%7Bjob%3A%27gh%3Ayegor256%2F0pdd%23135%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment] 2018-04-12 14:48
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment] 2018-04-12 15:03
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by 0crat** [comment] 2018-04-12 16:04
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by SilasReinagel** [comment] 2018-04-12 16:05
@yegor256 I have not been paid for the completion. Please re-open and close.

**Closed** 2018-04-13 06:39 UTC
Labels: bug, help wanted, scope

**Comment by 0crat** [comment] 2018-04-13 06:54
Order was finished: +30 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment] 2018-04-13 06:55
The job [#135](https://github.com/yegor256/0pdd/issues/135) is now out of scope
