### ISSUE TITLE
Don't mention estimate if it equal to 0

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#221] opened 2018-06-21 13:19 UTC
Looks like #70 wasn't fully fixed because `Estimate: 0 minutes` is still there. I guess that the check that was added, tests for the `nil` value but the estimation equals to zero.

Here is the quote from original requirements:

> Let's skip the estimate if it's equal to 0 and skip the role if it's equal to IMP.

CC @yegor256 @SilasReinagel

**Comment by 0crat** [comment] 2018-06-21 13:19
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-06-21 13:19
@php-coder[/z](https://www.0crat.com/u/php-coder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment] 2018-06-24 08:01
Job [#221](https://github.com/yegor256/0pdd/issues/221) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-06-24 08:01
Thanks for your contribution, @php-coder[/z](https://www.0crat.com/u/php-coder)! If you would be a member of [the project](https://www.0crat.com/p/C3T46CUJJ), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment] 2018-06-29 09:08
The job [#221](https://github.com/yegor256/0pdd/issues/221) assigned to @golyalpha[/z](https://www.0crat.com/u/golyalpha), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1800920465); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by golyalpha** [comment] 2018-07-03 07:14
@0crat resign

**Comment by 0crat** [comment] 2018-07-03 07:14
> @0crat resign ([here](https://github.com/yegor256/0pdd/issues/221#issuecomment-402036780))

@golyalpha The user @golyalpha[/z](https://www.0crat.com/u/golyalpha) resigned from [#221](https://github.com/yegor256/0pdd/issues/221), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-07-03 07:14
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @golyalpha[/z](https://www.0crat.com/u/golyalpha)

**Comment by 0crat** [comment] 2018-07-06 06:33
The job [#221](https://github.com/yegor256/0pdd/issues/221) assigned to @pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1870646611); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2018-07-11 06:37
@pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pdacostaporto** [comment] 2018-07-16 00:06
@0crat waiting for review #231

**Comment by 0crat** [comment] 2018-07-16 06:01
> @0crat waiting for review #231  ([here](https://github.com/yegor256/0pdd/issues/221#issuecomment-405128233))

@pdacostaporto The impediment for [#221](https://github.com/yegor256/0pdd/issues/221) was registered successfully by @pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto)

**Comment by pdacostaporto** [comment] 2018-07-16 13:51
@php-coder looks like #231 fixed this. Please close the issue.

**Comment by php-coder** [comment] 2018-07-18 16:09
@pdacostaporto No, unfortunately it doesn't fix it. Now the message contains "Estimate: 0 minutes,".

Here is an issue that was generated a few minutes ago: https://github.com/php-coder/mystamps/issues/926

**Comment by pdacostaporto** [comment] 2018-07-21 17:31
@php-coder Looks like the [current release](https://github.com/yegor256/0pdd/tree/0.30.3) does not have the change yet. Are you testing with master or should we wait for the next release?

**Comment by php-coder** [comment] 2018-07-22 10:06
> Are you testing with master or should we wait for the next release?

I'm testing on real @0pdd Perhaps, we should wait.

**Comment by lastk** [comment] 2019-05-27 05:32
@yegor256 there was still a bug here where it wasn't showing the estimates at all. #266 fix it.

**Closed** 2019-05-28 14:23 UTC
Labels: bug, scope

**Comment by yegor256** [comment] 2019-05-28 14:39
@rultor release, tag is `0.30.18`

**Comment by 0crat** [comment] 2019-05-28 16:56
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @php-coder[/z](https://www.0crat.com/u/php-coder) (its creator); I won't close the order; please, re-open it and ask @php-coder[/z](https://www.0crat.com/u/php-coder) to close it

**Comment by 0crat** [comment] 2019-06-03 10:00
@pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto) resigned from [#221](https://github.com/yegor256/0pdd/issues/221), since the job is not in scope anymore

**Comment by 0crat** [comment] 2019-06-03 10:00
The job [#221](https://github.com/yegor256/0pdd/issues/221) is now out of scope
